trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
      version: '3.7'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(version)'
  inputs:
    versionSpec: '$(version)'

- script: |
    python -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install setuptools
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run unit tests'

- script: |
    source venv/bin/activate
    mkdir artifact
    cp -r ./* artifact
    zip -r artifact.zip ./artifact
  displayName: Create a .ZIP file artifact

- task: PublishBuildArtifacts@1
  displayName: Publish build artifact
  inputs:
    pathToPublish: './artifact.zip'
    artifactName: artifact
    