trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
      version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(version)'
  displayName: 'Use Python $(version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    ls -a
  displayName: 'Show files'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
